# Generated by Django 3.0.5 on 2020-04-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grosir_1_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grosir_2_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grosir_3_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_grosir_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_grosir_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_grosir_3',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_end_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_end_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_end_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_harga_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_harga_2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_harga_3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_operator_1',
            field=models.CharField(blank=True, choices=[('0', '>=.'), ('1', '<=.'), ('2', '>.'), ('3', '<.')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_operator_2',
            field=models.CharField(blank=True, choices=[('0', '>=.'), ('1', '<=.'), ('2', '>.'), ('3', '<.')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_operator_3',
            field=models.CharField(blank=True, choices=[('0', '>=.'), ('1', '<=.'), ('2', '>.'), ('3', '<.')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_start_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_start_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tingkat_start_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
