# Generated by Django 3.0.3 on 2020-02-25 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tgl_pembayaran', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=0, max_digits=9)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PembayaranProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=0, max_digits=9)),
                ('pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Pembayaran')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='products',
            field=models.ManyToManyField(through='cashier.PembayaranProduct', to='cashier.Product'),
        ),
    ]
