# Generated by Django 3.0.4 on 2020-03-05 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20200304_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(db_index=True, max_length=128)),
                ('address', models.CharField(db_index=True, max_length=128)),
                ('contact_person', models.CharField(db_index=True, max_length=128)),
                ('office_phone', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Supplier'),
        ),
    ]
