# Generated by Django 3.0.5 on 2020-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20200419_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hargabertingkat',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='hargabertingkat',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='hargabertingkat',
            name='max_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hargabertingkat',
            name='min_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hargabertingkat',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tingkat_operator_1',
            field=models.CharField(blank=True, choices=[('0', '>='), ('1', '<='), ('2', '>'), ('3', '<')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tingkat_operator_2',
            field=models.CharField(blank=True, choices=[('0', '>='), ('1', '<='), ('2', '>'), ('3', '<')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tingkat_operator_3',
            field=models.CharField(blank=True, choices=[('0', '>='), ('1', '<='), ('2', '>'), ('3', '<')], max_length=3, null=True),
        ),
    ]
