# Generated by Django 3.0.5 on 2020-04-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_auto_20200420_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tingkat_end_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_end_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_end_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_harga_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_harga_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_harga_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_operator_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_operator_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_operator_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_start_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_start_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tingkat_start_3',
        ),
    ]
