# Generated by Django 3.0.5 on 2020-04-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_auto_20200420_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hargabertingkat',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hargabertingkat', to='cashier.Product'),
        ),
    ]
