# Generated by Django 3.0.3 on 2020-03-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_invoice_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Empty'), (1, 'Success'), (2, 'Cancel')], db_index=True, default=0),
        ),
    ]
