# Generated by Django 3.0.5 on 2020-04-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20200420_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Empty'), (1, 'Success'), (2, 'Pending')], db_index=True, default=0),
        ),
    ]
