# Generated by Django 3.0.4 on 2020-03-10 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20200307_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertbarang',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Product'),
        ),
        migrations.AlterField(
            model_name='convertbarang',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Unit'),
        ),
    ]
