# Generated by Django 3.0.3 on 2020-03-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_auto_20200310_0757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
