# Generated by Django 3.0.5 on 2020-05-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_auto_20200425_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
