# Generated by Django 3.0.4 on 2020-03-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_auto_20200310_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertbarang',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cashier.Product'),
        ),
    ]
