# Generated by Django 3.0.4 on 2020-04-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_auto_20200425_0135'),
        ('cashier', '0002_expenses'),
    ]

    operations = [
    ]
