# Generated by Django 3.0.4 on 2020-06-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_sale_price'),
        ('cashier', '0007_merge_20200430_1237'),
    ]

    operations = [
    ]
