# Generated by Django 3.0.3 on 2020-03-11 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_auto_20200310_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_cashier', to=settings.AUTH_USER_MODEL),
        ),
    ]
