# Generated by Django 3.0.4 on 2020-03-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20200309_0657'),
        ('cashier', '0007_auto_20200310_1111'),
    ]

    operations = [
    ]
