# Generated by Django 3.0.4 on 2020-03-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_merge_20200310_1136'),
        ('cashier', '0007_auto_20200310_1207'),
    ]

    operations = [
    ]
