# Generated by Django 3.0.4 on 2020-06-13 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_merge_20200613_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('address', models.CharField(db_index=True, max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('profession', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Onprocess'), (1, 'Success')], db_index=True, default=0),
        ),
    ]
