# Generated by Django 3.0.3 on 2020-03-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0009_merge_20200310_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertbarang',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convert_barang', to='cashier.Product'),
        ),
    ]
