# Generated by Django 3.0.3 on 2020-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0010_auto_20200311_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grosir_1_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='grosir_2_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='grosir_3_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_grosir_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_grosir_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_grosir_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
