# Generated by Django 3.0.5 on 2020-06-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0010_auto_20200615_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_member', to='cashier.Member'),
        ),
    ]
