# Generated by Django 3.0.5 on 2020-07-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0014_auto_20200630_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Onprocess'), (1, 'Success')], db_index=True, default=0),
        ),
    ]
