# Generated by Django 3.0.5 on 2020-07-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0016_auto_20200709_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='kode',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.ProductCategory', verbose_name='kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimal_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='batas minimal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='nama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='harga beli'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='eceran'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='stok'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Unit', verbose_name='satuan'),
        ),
    ]
