# Generated by Django 3.0.5 on 2020-07-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0018_auto_20200710_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grosir_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='grosir_2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='grosir_3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
    ]
