# Generated by Django 3.0.5 on 2020-07-11 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0019_auto_20200710_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.ProductCategory', verbose_name='kategori'),
        ),
        migrations.CreateModel(
            name='ProductTemp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='nama')),
                ('barcode', models.CharField(max_length=128)),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='stok')),
                ('minimal_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='batas minimal')),
                ('purchase_price', models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='harga beli')),
                ('selling_price', models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='eceran')),
                ('grosir_1', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('grosir_2', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('grosir_3', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_index=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.ProductCategory', verbose_name='kategori')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Supplier')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Unit', verbose_name='satuan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
