# Generated by Django 3.0.5 on 2020-07-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0020_auto_20200711_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='nama'),
        ),
    ]
