# Generated by Django 3.0.5 on 2020-07-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0021_auto_20200711_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
