# Generated by Django 3.0.5 on 2020-07-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0022_auto_20200711_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemp',
            name='minimal_stock',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='batas minimal'),
        ),
        migrations.AlterField(
            model_name='producttemp',
            name='stock',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='stok'),
        ),
    ]
