# Generated by Django 3.0.5 on 2020-07-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0024_auto_20200711_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTempTesting',
        ),
    ]
