# Generated by Django 3.0.5 on 2020-07-16 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0025_delete_producttemptesting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profession',
        ),
        migrations.AlterField(
            model_name='convertbarang',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convert_barang', to='cashier.Product', verbose_name='produk'),
        ),
        migrations.AlterField(
            model_name='convertbarang',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='harga beli'),
        ),
        migrations.AlterField(
            model_name='convertbarang',
            name='quantity',
            field=models.IntegerField(verbose_name='kuantiti'),
        ),
        migrations.AlterField(
            model_name='convertbarang',
            name='selling_price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='harga jual'),
        ),
        migrations.AlterField(
            model_name='convertbarang',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Unit', verbose_name='satuan'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='kasir'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='biaya'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tanggal'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='information',
            field=models.CharField(db_index=True, max_length=128, verbose_name='informasi'),
        ),
        migrations.AlterField(
            model_name='hargabertingkat',
            name='max_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='max qty'),
        ),
        migrations.AlterField(
            model_name='hargabertingkat',
            name='min_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='min qty'),
        ),
        migrations.AlterField(
            model_name='hargabertingkat',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='harga jual'),
        ),
        migrations.AlterField(
            model_name='income',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='kasir'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tanggal'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='alamat'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='nama'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='no telp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='nama produk'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='nama kategori'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=128, verbose_name='nama satuan'),
        ),
    ]
