# Generated by Django 3.0.5 on 2020-07-16 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0026_auto_20200716_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='tunai'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_cashier', to=settings.AUTH_USER_MODEL, verbose_name='kasir'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='kembalian'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_cashier', to=settings.AUTH_USER_MODEL, verbose_name='kasir'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tanggal'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_product', to='cashier.Product', verbose_name='produk'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='harga'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale', to='cashier.Product', verbose_name='produk'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='alamat'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='nama perusahaan'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='nama kontak'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='office_phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='no telp kantor'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='no HP'),
        ),
    ]
