# Generated by Django 3.0.4 on 2020-07-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0027_auto_20200716_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Debt'), (1, 'Cash')], db_index=True, default=1),
        ),
    ]
