# Generated by Django 3.0.4 on 2020-07-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0028_purchase_payment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
    ]
