# Generated by Django 3.0.5 on 2020-07-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0028_purchase_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='harga beli'),
        ),
    ]
