# Generated by Django 3.0.5 on 2020-08-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0029_purchasedetail_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hargabertingkat',
            name='max_quantity',
        ),
    ]
