# Generated by Django 3.0.5 on 2020-08-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0030_remove_hargabertingkat_max_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grosir_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grosir_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grosir_3',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
