# Generated by Django 3.0.4 on 2020-08-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0029_auto_20200731_1045'),
        ('cashier', '0032_auto_20200801_1932'),
    ]

    operations = [
    ]
