# Generated by Django 3.0.5 on 2020-08-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0033_merge_20200804_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Onprocess'), (1, 'Success'), (2, 'Cancel')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Onprocess'), (1, 'Success'), (2, 'Cancel')], db_index=True, default=0),
        ),
    ]
