# Generated by Django 3.0.4 on 2020-08-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0033_merge_20200804_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.CharField(db_index=True, default='R', max_length=128, verbose_name='kode'),
        ),
        migrations.AddField(
            model_name='income',
            name='invoice',
            field=models.CharField(db_index=True, default='G', max_length=128, verbose_name='kode'),
        ),
    ]
