# Generated by Django 3.0.4 on 2020-08-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0034_auto_20200807_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='invoice',
            field=models.CharField(db_index=True, default='RZ00000000000000', max_length=128, verbose_name='kode'),
        ),
        migrations.AlterField(
            model_name='income',
            name='invoice',
            field=models.CharField(db_index=True, default='GZ00000000000000', max_length=128, verbose_name='kode'),
        ),
    ]
