# Generated by Django 3.0.4 on 2020-08-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0035_auto_20200807_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='invoice',
            field=models.CharField(db_index=True, max_length=128, verbose_name='kode'),
        ),
        migrations.AlterField(
            model_name='income',
            name='invoice',
            field=models.CharField(db_index=True, max_length=128, verbose_name='kode'),
        ),
    ]
