# Generated by Django 3.0.5 on 2020-08-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0036_auto_20200807_1459'),
        ('cashier', '0034_auto_20200809_0632'),
    ]

    operations = [
    ]
