# Generated by Django 3.0.5 on 2020-09-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0037_merge_20200809_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Debt'), (2, 'Cash')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Onprocess'), (2, 'Success'), (3, 'Cancel')], db_index=True, default=1),
        ),
    ]
